version: 2

project_name: ts-redir

env:
  - CGO_ENABLED=0

dist: dist

before:
  hooks:
    - go mod tidy

builds:
  - id: ts-redir
    main: ./cmd/ts-redir
    binary: ts-redir
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    flags:
      - -trimpath
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - formats: [ 'tar.gz' ]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - images/**/*

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}"

changelog:
  use: git
